### ISSUE TITLE
Problema com Hash

### ISSUE THREAD

**Issue by FabioZumbi12** [luizwbr/Bcash-VirtueMart-3#1]
Baixe este modulo tambem pro Virtuemart mas esta dando problema com Hash: http://prntscr.com/c3c16e

O que devo fazer? Ja coloquei o que precisava nas configurações, só o ID da plataforma que não sei o que é (e não tem nada sobre isso no seu tutorial de configuração).

Obrigado desde já.

**Comment by FabioZumbi12** [comment]
Depois que eu percebi que o botão de "Ativar Recurso" era pra ativar a validação por "Hash" pois ativei pensando que era pra ativar o retorno de URL.

Aproveitando a dúvida e depois fecho essa issue. Não preciso configurar o url de retorno pro BCash? Não fiz nenhuma venda com ele ainda então não tive como testar.

Obrigado.

**Comment by luizwbr** [comment]
Não precisa configurar o retorno, já está no plugin implementado ;)
