### ISSUE TITLE
Erro no front end

### ISSUE THREAD

**Issue by Alexandre-df** [luizwbr/Bcash-VirtueMart-3#2]
Bom dia

Joomla 3.6.5 e Virtuemart 3.20

No front end aparece o erro:

STRICT STANDARDS: DECLARATION OF PLGVMPAYMENTBCASH::SETCARTPRICES() SHOULD BE COMPATIBLE WITH VMPSPLUGIN::SETCARTPRICES(VIRTUEMARTCART $CART, &$CART_PRICES, $METHOD, $PROGRESSIVE = TRUE) IN /HOME/STORAGE/0/8B/B0/FACILCARD/PUBLIC_HTML/KEYSMARTER/PLUGINS/VMPAYMENT/BCASH/BCASH.PHP ON LINE 902

**Comment by luizwbr** [comment]
Corrigido no commit https://github.com/luizwbr/Bcash-VirtueMart-3/commit/15922c70186164075d17fce3a08c8e1a716b2388
